# docker-compose.yml
version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    networks:
      - classroom
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "5173:5173"
    networks:
      - classroom
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - classroom

networks:
  classroom:
    driver: bridge