# docker-compose.yml
version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"