# Usamos la imagen oficial de Nginx
FROM nginx:latest

# Copiamos el archivo de configuración de Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exponemos el puerto 80
EXPOSE 80

# Iniciamos Nginx cuando el contenedor se lance
CMD ["nginx", "-g", "daemon off;"]